return {
    Default = 'Common',
    Contents = {
        Common = {
            luckInfluence = 0,
            color = Color3.new(0.247059, 1, 0.019608),
            gradient = ColorSequence.new(
               {ColorSequenceKeypoint.new(0.00, Color3.new(0.247059, 1, 0.019608)), 
                ColorSequenceKeypoint.new(0.50, Color3.new(0.247059, 1, 0.019608)), 
                ColorSequenceKeypoint.new(0.61, Color3.new(0.141176, 0.513725, 0.031373)), 
                ColorSequenceKeypoint.new(1.00, Color3.new(0.141176, 0.513725, 0.031373))}
            ),
        },
        UnCommon = {
            luckInfluence = 0.2,
            color = Color3.new(0.247059, 1, 0.019608),
            gradient = ColorSequence.new(
               {ColorSequenceKeypoint.new(0.00, Color3.new(0.247059, 1, 0.019608)), 
                ColorSequenceKeypoint.new(0.50, Color3.new(0.247059, 1, 0.019608)), 
                ColorSequenceKeypoint.new(0.61, Color3.new(0.141176, 0.513725, 0.031373)), 
                ColorSequenceKeypoint.new(1.00, Color3.new(0.141176, 0.513725, 0.031373))}
            ),
        },
    }
}